apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  #imagePullPolicy: Never
  minSyncReplicas: 1
  maxSyncReplicas: 1

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 2Gi

  backup:
    barmanObjectStore:
      destinationPath: "s3://cnp"
      endpointURL: "http://sos-ch-gva-2.exo.io"
      s3Credentials:
        accessKeyId:
          name: sks-creds
          key: SKS_ACCESS_KEY
        secretAccessKey:
          name: sks-creds
          key: SKS_SECRET_KEY
      data:
        immediateCheckpoint: true
    retentionPolicy: "1d"
