apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  #imagePullPolicy: Never

  storage:
    size: 1Gi

  bootstrap:
    recovery:
      backup:
        name: backup-test
